eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname:192.168.1.1}:${eureka.server.port:18761}/eureka/
  instance:
    prefer-ip-address: true


feign.hystrix.enabled: false

hystrix:
  command:
    default:
      circuitBreaker:
        sleepWindowInMilliseconds: 30000
        requestVolumeThreshold: 10
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 100000



#redis哨兵模式集群
spring.redis.sentinel.master = mymaster
spring.redis.sentinel.nodes = 192.168.1.1:26379,192.168.1.2:26379,192.168.1.3:26379
spring.redis.password = redis
spring.redis.database = 9
spring.redis.timeout = 30000
spring.redis.pool.max-active = 20


#Hikari数据库连接池
spring.datasource.type = com.zaxxer.hikari.HikariDataSource
spring.datasource.driverClassName = com.mysql.jdbc.Driver
spring.datasource.url = jdbc:mysql://192.168.1.1:3306/test?tinyInt1isBit=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull&useSSL=false
spring.datasource.username = test
spring.datasource.password = test
spring.datasource.hikari.connection-test-query = SELECT 1 FROM DUAL
spring.datasource.hikari.minimum-idle = 20
spring.datasource.hikari.maximum-pool-size = 100
spring.datasource.hikari.pool-name = ${spring.application.name}-CP
spring.datasource.hikari.idle-timeout = 10000
spring.datasource.hikari.cachePrepStmts = true
spring.datasource.hikari.prepStmtCacheSize = 250
spring.datasource.hikari.prepStmtCacheSqlLimit = 2048
spring.datasource.hikari.leakDetectionThreshold = 2000


#mybatis配置
mybatis.configuration.map-underscore-to-camel-case = true
mybatis.configuration.default-fetch-size = 100
mybatis.configuration.default-statement-timeout = 30
mybatis.mapperLocations = classpath*:com/demo/*.xml


#rabbitmq集群
spring.rabbitmq.host = ${rabbitmq.server.hostname:192.168.1.1,192.168.1.2,192.168.1.3}
spring.rabbitmq.port = ${rabbitmq.server.port:5672}
spring.rabbitmq.username = admin
spring.rabbitmq.password = admin


#elasticjob的zookeeper配置
elasticjob.zookeeper.server-lists = 192.168.1.1:2181,192.168.1.2:2181,192.168.1.3:2181
elasticjob.zookeeper.namespace = elastic-job


#最大连接数
httpclient.maxTotal = 200
#分配给Route的最大连接数，Route指与服务器的连接链路
httpclient.defaultMaxPerRoute = 80
#与服务器创建连接的超时时间
httpclient.connectTimeout = 1000
#从连接池获取连接的超时时间
httpclient.connectionRequestTimeout = 500
#socket传输数据的超时时间
httpclient.socketTimeout = 10000
#提交请求前测试连接是否可用
httpclient.staleConnectionCheckEnabled = true


#kafka配置
spring.kafka:
    binlog-consumer:
      bootstrap-servers: 192.168.1.1:9092,192.168.1.2:9092,192.168.1.3:9092
      auto-offset-reset: earliest
      enable-auto-commit: false
      group-id: kafka-binlog-consumer-group
      max-poll-records: 1000
      max-partition-fetch-bytes: 52428800
      concurrency: 2

